### ISSUE TITLE
Pin code after downloading it

### ISSUE THREAD

**Issue by folex** [fluencelabs/rust-peer#761]
When a node downloads a code, it should send `pin/add` request to the (local) IPFS node, so code is persisted on that node.

**Comment by swarna1101** [comment]
Here is an example of how you might use the Rust programming language and the rust-ipfs library to download code from an IPFS node and send a pin request to the node to preserve the code:

```
use ipfs::{Client, IpfsClient, Result};

fn main() -> Result<()> {
    // Create an IPFS client
    let client = IpfsClient::default();

    // Download code from IPFS node
    let code = client.cat("/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG")?;

    // Send pin request to IPFS node to preserve the code
    client.pin_add("/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG")?;

    Ok(())
}
```

**Comment by folex** [comment]
outdated issue
